package com.example.ecommerce.controller;

import com.example.ecommerce.dto.StatisticsResponse;
import com.example.ecommerce.model.DiscountCode;
import com.example.ecommerce.service.DiscountService;
import com.example.ecommerce.service.OrderService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/admin")
public class AdminController {
    private final DiscountService discountService;
    private final OrderService orderService;

    @Autowired
    public AdminController(DiscountService discountService, OrderService orderService) {
        this.discountService = discountService;
        this.orderService = orderService;
    }

    @GetMapping("/generate-discount") // getting discount generated by admin to get used by the end user
    public ResponseEntity<DiscountCode> generateDiscountCode() {
        DiscountCode discountCode = discountService.generateDiscountCode();
        return ResponseEntity.ok(discountCode);
    }

    @GetMapping("/statistics") // provide summary to the admin of how much item purchased with total amount earned, d
    // total amount of discount used , discount code used
    public ResponseEntity<StatisticsResponse> getStatistics() {
        StatisticsResponse statistics = orderService.getStatistics();
        return ResponseEntity.ok(statistics);
    }
}
